// Next.js wraps every page in this component, so anything that should apply
// to the whole site lives here — the html/body tags, fonts, and page metadata
// like the browser tab title.
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Loads the "Geist" fonts from Google and turns them into CSS variables that
// globals.css uses for regular text and monospace text.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Shows up as the browser tab title and in search results.
export const metadata = {
  title: "Welcome to Divine's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // children is whichever page is currently being viewed — Next.js fills this in automatically.
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
